version: '3.8'

services:
  # --- VERİTABANI ---
  db:
    image: postgres:15
    container_name: logistics_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: logistics_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # --- MESAJ KUYRUĞU ---
  redis:
    image: redis:alpine
    container_name: logistics_redis
    ports:
      - "6379:6379"

  # --- AUTH SERVİSİ ---
  auth-service:
    build:
      context: .
      dockerfile: services/auth/Dockerfile
    container_name: auth-service
    ports:
      - "8001:8000"
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/logistics_app
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis

  # --- ORDER SERVİSİ ---
  order-service:
    build:
      context: .
      dockerfile: services/order/Dockerfile
    container_name: order-service
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/logistics_app
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  # --- COMMUNICATION API ---
  communication-service:
    build:
      context: .
      dockerfile: services/communication/Dockerfile
    container_name: communication-api
    ports:
      - "8003:8000"
    env_file: .env
    depends_on:
      - db
      - redis

  # --- CHATBOT SERVİSİ (Gemini AI Agent & Gateway) ---
  chatbot-service:
    build:
      context: .
      dockerfile: services/chatbot/Dockerfile
    container_name: chatbot-service
    ports:
      - "8004:8000"
    env_file: .env
    volumes:
      - .:/app # Kodun canlı güncellenmesi için
    environment:
      - PYTHONUNBUFFERED=1 # Logların anında terminale düşmesini sağlar
      - GROQ_API_KEY=${GROQ_API_KEY}
      - DATABASE_URL=postgresql://user:password@db:5432/logistics_app
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

# --- VOLUMES ---
volumes:
  postgres_data: